#pragma once

#include <rb/core/error/package.hpp>
#include <rb/core/iter/package.hpp>
#include <rb/core/memory/package.hpp>
#include <rb/core/meta/package.hpp>
#include <rb/core/traits/package.hpp>

#include <rb/core/assert.hpp>
#include <rb/core/attributes.hpp>
#include <rb/core/bits.hpp>
#include <rb/core/builtins.hpp>
#include <rb/core/byte.hpp>
#include <rb/core/compiler.hpp>
#include <rb/core/CompilerInfo.hpp>
#include <rb/core/endian.hpp>
#include <rb/core/enums.hpp>
#include <rb/core/ErrorCode.hpp>
#include <rb/core/exchange.hpp>
#include <rb/core/export.hpp>
#include <rb/core/features.hpp>
#include <rb/core/Flags.hpp>
#include <rb/core/helpers.hpp>
#include <rb/core/in_place.hpp>
#include <rb/core/int128.hpp>
#include <rb/core/invoke.hpp>
#include <rb/core/keywords.hpp>
#include <rb/core/limits.hpp>
#include <rb/core/move.hpp>
#include <rb/core/Option.hpp>
#include <rb/core/os.hpp>
#include <rb/core/processor.hpp>
#include <rb/core/quorem.hpp>
#include <rb/core/requires.hpp>
#include <rb/core/sanitizers.hpp>
#include <rb/core/SourceLocation.hpp>
#include <rb/core/strings.hpp>
#include <rb/core/swap.hpp>
#include <rb/core/types.hpp>
#include <rb/core/Version.hpp>

#include <rb/rb_version.hpp>
