set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_BUILD_ID 25A354)
set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_ID macOS)
set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_ID_LIKE apple)
set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_NAME macOS)
set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_VERSION "Tahoe 26")
set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_VERSION_CODENAME Tahoe)
set(CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_VERSION_ID 26)

list(APPEND CMAKE_GET_OS_RELEASE_FALLBACK_RESULT
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_BUILD_ID
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_ID
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_ID_LIKE
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_NAME
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_VERSION
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_VERSION_CODENAME
    CMAKE_GET_OS_RELEASE_FALLBACK_RESULT_VERSION_ID
)

# https://www.freedesktop.org/software/systemd/man/latest/os-release.html
#BUG_REPORT_URL=`https://bugs.launchpad.net/ubuntu/`
#HOME_URL=`https://www.ubuntu.com/`
#ID=`ubuntu`
#ID_LIKE=`debian`
#NAME=`Ubuntu`
#PRETTY_NAME=`Ubuntu 20.04.2 LTS`
#PRIVACY_POLICY_URL=`https://www.ubuntu.com/legal/terms-and-policies/privacy-policy`
#SUPPORT_URL=`https://help.ubuntu.com/`
#UBUNTU_CODENAME=`focal`
#VERSION=`20.04.2 LTS (Focal Fossa)`
#VERSION_CODENAME=`focal`
#VERSION_ID=`20.04`
