if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang$")
    set(COMPILER_CLANG ON)
    if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
        set(COMPILER_CLANG_MSVC ON)
        set(COMPILER_MSVC_LIKE ON)
    elseif(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
        set(COMPILER_CLANG_GNU ON)
    endif()
else()
    set(COMPILER_CLANG OFF)
endif()

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(COMPILER_GCC ON)
else()
    set(COMPILER_GCC OFF)
endif()

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    set(COMPILER_MSVC ON)
    set(COMPILER_MSVC_LIKE ON)
    set(COMPILER_CLANG_MSVC OFF)
else()
    set(COMPILER_MSVC OFF)
endif()

if(${COMPILER_GCC})
    add_compile_options(-fdiagnostics-color=always)

    add_compile_options(-Wall)
    add_compile_options(-Wextra)
    add_compile_options(-pedantic)
    add_compile_options(-Wshadow=local)

    add_compile_options(-Wno-unknown-pragmas)
    add_compile_options(-Wno-nonnull-compare)
    add_compile_options(-Wno-parentheses)
    # add_compile_options(-fanalyzer)
elseif(${COMPILER_CLANG})
    add_compile_options(-fcolor-diagnostics)

    add_compile_options(-Wall)
    add_compile_options(-Wextra)
    add_compile_options(-pedantic)
    add_compile_options(-Wthread-safety)
    add_compile_options(-Wshadow -Wshadow-field -Wshadow-field-in-constructor-modified -Wshadow-uncaptured-local)

    add_compile_options(-Wno-unknown-pragmas)
    add_compile_options(-Wno-logical-op-parentheses)
    add_compile_options(-Wno-language-extension-token)
    add_compile_options(-Wno-gnu-statement-expression-from-macro-expansion)
    if(${COMPILER_CLANG_MSVC})
        add_compile_options(/EHsc)
    endif()
elseif(${COMPILER_MSVC})
    cmake_host_system_information(RESULT NUMBER_OF_LOGICAL_CORES QUERY NUMBER_OF_LOGICAL_CORES)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP${NUMBER_OF_LOGICAL_CORES}")

    add_compile_options(/Wall)
    add_compile_options(/EHsc)
    add_compile_options(/analyze)
    # disable "unknown pragma" warnings
    add_compile_options(/wd4068)
    # disable "exception-filter expression is the constant EXCEPTION_EXECUTE_HANDLER" warnings
    add_compile_options(/wd6320)
endif()
